# Generated by Django 5.1.1 on 2024-10-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter the Employee's First Name", max_length=100)),
                ('last_name', models.CharField(help_text="Enter the Employee's Last Name", max_length=100)),
                ('position', models.CharField(help_text="Enter the Employee's Job Position", max_length=100)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
    ]
