# Generated by Django 5.1.1 on 2024-10-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter the Client's First Name", max_length=100)),
                ('last_name', models.CharField(help_text="Enter the Client's Last Name", max_length=100)),
                ('address', models.CharField(help_text="Enter the Client's Address", max_length=100)),
                ('phone', models.CharField(help_text="Enter the Client's Phone Number", max_length=12)),
                ('email', models.EmailField(help_text="Enter the Client's Email", max_length=100)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
    ]
